config/routes.rb
Blogcast::Application.routes.draw do
  root :to => "posts#index"

  resources :posts do
    resources :comments do
      collection do
        post :preview
      end
      member do
        delete :mark_as_spam
      end
    end
    
    resources :spams do
      collection do
        delete :incinerate
      end
      member do
        delete :mark_as_ham
      end
    end
  end
  
  resources :drafts
  
  match 'archives', :to => 'archives#index', :as => :archives, :via => [:get]
  
  match 'admin', :to => 'user_sessions#new', :as => :admin, :via => [:get]
  match 'logout', :to => 'user_sessions#destroy', :as => :logout, :via => [:delete]
  resource :user_sessions
  
  resources :users
  
  match 'sitemap', :to => 'sitemap#index', :via => [:get]
  
  match '*a', :to => 'errors#routing', :via => [:get]
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :initials, :login, :email, :password
  
  acts_as_authentic
  attr_accessible :name, :initials, :login, :email, :password, :password_confirmation
  
  def self.find_by_login_or_email(login)
    User.find_by_login(login) || User.find_by_email(login)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user
  
  #/users
  def index
    @users = User.all
  end
  
  #/users/1
  def show
  end
  
  #/users/new
  def new
    @user = User.new
  end
  
  #/users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      redirect_to users_path
    else
      render :action => "new"
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
      redirect_to users_path
    else
      render :action => "edit"
    end
  end
  
  #/users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end
end

app/views/users/edit.html.erb
<% content_for :title do %>
Modifier le compte utilisateur
<% end %>

<% content_for :robots do %> 
<meta name="robots" content="noarchive"/>
<meta name="robots" content="noindex, nofollow"/>
<% end %>

<h2>Gestion des utilisateurs de BlogCast</h2>

<h3>Edit the persona for this user</h3>

<div class="posts archives users">

<div class="comments_canvas">
	<div id="post_a_comment">
	<h2></h2>
	<%= form_for(@user) do |f| %>
	<div id="edit_user_canvas">
		<fieldset>
			<div class="form-field">
				<%= f.label :name %>
				<%= f.text_field :name, :size => "40" %>
			</div>
			
			<div class="form-field">
				<%= f.label :initials %>
				<%= f.text_field :initials, :size => "40" %> 
			</div>
			
			<div class="form-field">
				<%= f.label :login %>
				<%= f.text_field :login, :size => "40" %> 
			</div>
			
			<div class="form-field">
				<%= f.label :email %>
				<%= f.text_field :email, :size => "40" %> 
			</div>
			
			<div class="form-field">
				<%= f.label :password, f.object.new_record? ? nil : "Change Password" %>
				<%= f.password_field :password, :size => "40" %> 
			</div>
			
			<div class="form-field">
				<%= f.label :password_confirmation, "Password Confirmation" %>
				<%= f.password_field :password_confirmation, :size => "40" %> 
			</div>
		</fieldset>
		
		<fieldset>
			<div class="form-submit">
				<%= f.submit "Update this user" %>
			</div>
		</fieldset>
	</div><!-- edit_user_canvas -->
	<% end %>
	</div><!-- post_a_comment -->
</div><!-- comments_canvas -->

</div><!-- users -->

<% content_for :sidebar do %>
<div class="sidebar">

</div><!--sidebar-->
<% end %>

app/views/users/index.html.erb
<% content_for :title do %>
BlogCast::Gestion des utilisateurs de BlogCast
<% end %>

<% content_for :robots do %> 
<meta name="robots" content="noarchive"/>
<meta name="robots" content="noindex, nofollow"/>
<% end %>

<h2>Gestion des utilisateurs de BlogCast</h2>

<h3>Membres actuels</h3>

<div class="archives users">
	<ul>
	<% for user in @users %>
		<li><%= link_to user.name, edit_user_path(user) %>

			<%= link_to user_path(user), :confirm => "Are you sure you want to delete this user?", :method => :delete do %>
			<%= image_tag "delete.png", :alt => "delete draft", :title => "delete draft" %>
			<% end %>
		</li>
	<% end %>
	</ul>
</div>

<% content_for :sidebar do %>
<div class="sidebar">
	<div class="block-content user_management">
		<% link_to "Nouvel utilisateur", new_user_path %>
		<%= link_to new_user_path do %>
		<%= image_tag "doc_plus.png", :alt => "Ajouter un utilisateur", :title => "Ajouter un utilisateur" %>
		<% end %>
	</div><!--block-content-->
</div><!--sidebar-->
<% end %>

app/views/users/new.html.erb
<% content_for :title do %>
Create User
<% end %>

<% content_for :robots do %> 
<meta name="robots" content="noarchive"/>
<meta name="robots" content="noindex, nofollow"/>
<% end %>

<h2>Manage Blog Users</h2>

<h3>Create the persona for this user</h3>

<div class="posts archives users">

<div class="comments_canvas">
	<div id="post_a_comment">
	<h2></h2>
	<%= form_for(@user) do |f| %>
	<div id="edit_user_canvas">
		<fieldset>
			<div class="form-field">
				<%= f.label :name %>
				<%= f.text_field :name, :size => "40" %>
			</div>
			
			<div class="form-field">
				<%= f.label :initials %>
				<%= f.text_field :initials, :size => "40" %> 
			</div>
			
			<div class="form-field">
				<%= f.label :login %>
				<%= f.text_field :login, :size => "40" %> 
			</div>
			
			<div class="form-field">
				<%= f.label :email %>
				<%= f.text_field :email, :size => "40" %> 
			</div>
			
			<div class="form-field">
				<%= f.label :password, f.object.new_record? ? nil : "Change Password" %>
				<%= f.password_field :password, :size => "40" %> 
			</div>
			
			<div class="form-field">
				<%= f.label :password_confirmation, "Password Confirmation" %>
				<%= f.password_field :password_confirmation, :size => "40" %> 
			</div>
		</fieldset>
		
		<fieldset>
			<div class="form-submit">
				<%= f.submit "Create this user" %>
			</div>
		</fieldset>
	</div><!-- edit_user_canvas -->
	<% end %>
	</div><!-- post_a_comment -->
</div><!-- comments_canvas -->

</div><!-- users -->

<% content_for :sidebar do %>
<div class="sidebar">

</div><!--sidebar-->
<% end %>