config/routes.rb
Blogcast::Application.routes.draw do
  root :to => "posts#index"

  resources :posts do
    resources :comments do
      collection do
        post :preview
      end
      member do
        delete :mark_as_spam
      end
    end
    
    resources :spams do
      collection do
        delete :incinerate
      end
      member do
        delete :mark_as_ham
      end
    end
  end
  
  resources :drafts
  
  match 'archives', :to => 'archives#index', :as => :archives, :via => [:get]
  
  match 'admin', :to => 'user_sessions#new', :as => :admin, :via => [:get]
  match 'logout', :to => 'user_sessions#destroy', :as => :logout, :via => [:delete]
  resource :user_sessions
  
  resources :users
  
  match 'sitemap', :to => 'sitemap#index', :via => [:get]
  
  match '*a', :to => 'errors#routing', :via => [:get]
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_many :spams, :dependent => :destroy
  
  validates_presence_of :title, :content
  
  attr_accessible :title, :content, :markdown, :author, :commentable
  
  def to_param
    #1st: Removes all non alphanumeric characters from the string.
		#2nd: No more than one of the separator in a row.
		#3rd: Remove leading/trailing separator.
    "#{id}-#{title.downcase.gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_user, :except => [:index, :show]
  
  # GET /posts
  def index
    @posts = Post.all(:select => "title, author, id, content, posted_at", :order => "posted_at DESC", :limit => 15) 
    
    respond_to do |format|
      format.html
      #format.xml { render :xml => @posts  }
      #format.json { render :json => @posts }
      format.rss { render :layout => false } #index.rss.builder
    end
  end

  # GET /posts/1
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  def create
    
    @post = Post.new(params[:post]) #Need this here just in-case saving the draft fails.
    
    if params[:save_post]
      @post.commentable = true
      @post.posted_at = Time.now
      @post.author = current_user.name

      #Save both HTML and Markdown
      @post.content = BlueCloth.new(@post.markdown).to_html
      
      if @post.save
        redirect_to(@post, :notice => 'Post was successfully created.')
      else
        render :action => "new"
      end
    end
    
    if params[:save_draft]
      @draft = Draft.new(params[:post])
      
      @draft.author = current_user.name
      @draft.content = BlueCloth.new(@draft.markdown).to_html
      
     if @draft.save
        redirect_to(drafts_url, :notice => 'Draft was successfully created.')
      else
        render :action => "new"
      end
    end
    
  end

  # PUT /posts/1
  def update
    @post = Post.find(params[:id])
    
    #Save both HTML and Markdown
    #Also use this method to toggle comments on and off
    #So, need to make sure :markdown attr is present so we know its an edit update
    if params[:post][:markdown]
      params[:post][:content]  = BlueCloth.new(params[:post][:markdown]).to_html
    end

    if @post.update_attributes(params[:post])
      redirect_to(@post, :notice => 'Post was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /posts/1
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to(posts_url)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def description(content)
    sanitize(content.gsub(/<code[^<]*<\/code>/, ""), :tags => %w(), :attributes => %w()).gsub(/[\r\n?]/, " ").squeeze(" ").gsub(/\"/, "'")[0..250].strip
  end
end

app/views/posts/_meta.html.erb
<% if post.comments.count == 0 %>
<%= link_to "Laisser un commentaire", post_path(post, :anchor => "comments") %>
<% else %>
<%= link_to pluralize(post.comments.count, "commentaire"), post_path(post, :anchor => "comments") %> 
dernier commentaire laissé par <%= post.comments.all.last.name %>
<% end %>

app/views/posts/edit.html.erb
<% content_for :title do %> 
Edit Post
<% end %>

<% content_for :robots do %> 
<meta name="robots" content="noarchive"/>
<meta name="robots" content="noindex, nofollow"/>
<% end %>

<% content_for :modstyles do %> 
<%= stylesheet_link_tag "modstyles" %>
<% end %>

<% content_for :modjs do %>
<%= javascript_include_tag "showdown" %>
<%= javascript_include_tag "wmd" %>
<%= javascript_include_tag "textarearesizer" %>
<%= javascript_include_tag "elastic" %>
<% end %>

<div class="post">
	<h2><%= link_to @post.title, post_path, :class => "article" %>
	<span class="nobreak">
		<span class="author"><%= @post.author %></span>
		<span class="date"><%= @post.posted_at.strftime("%b %d") %></span>
	</span>
	</h2>
	
	<p class="meta">
		<% if @post.comments.count == 0 %>
		<%= link_to "Laisser un commentaire", post_path(@post, :anchor => "comments") %>
		<% else %>

		<%= link_to pluralize(@post.comments.count, "commentaire"), post_path(@post, :anchor => "comments") %> dernier commentaire par <%= @post.comments.last.name %>
		<% end %>	
	</p>
		
	<div id="wmd-preview" class="entry"></div>
</div><!--post-->

<% content_for :sidebar do %>

<div class="sidebar">
<%= form_for(@post) do |f| %>
	<div id="title-container">
		<%= f.text_field :title %>
	</div>
	
	<div id="wmd-container">
	<div id="wmd-button-bar"></div>
	
	<%= f.text_area :markdown, :id => "wmd-input", :cols => "92", :rows => "15" %>
	
	</div><!--wmd-container-->

	<ul class="options form-submit">
		<li class="right"><%= f.submit "Enregistrer", :confirm => "Etes-vous sûrs de vouloir mettre à jour cet article ?" %></li>
	</ul>
<% end %>
</div><!--sidebar-->

<% end %>

app/views/posts/index.html.erb
<% content_for :title do %>Blogcast::Première plateforme Rails de Blogging <% end %>

<% content_for :description do %> <% end %>

<% if current_user %>
<% content_for :robots do %> 
<meta name="robots" content="noarchive"/>
<meta name="robots" content="noindex, nofollow"/>
<% end %>
<% end %>

<% if @posts.count == 0 %>

<% if current_user %>
<div class="post">
	<h2>Allez! au boulot</h2>
  <p class="meta"><%= link_to "Créez", :controller => "posts", :action => "new" %> votre premier article. </p>
</div>
<% else %>
  <div class="post"></div>
<% end %>

<% else %>

<% for post in @posts %>
<div class="post">
	<h2><%= link_to post.title, post %>
	<span class="nobreak">
		<span class="author"><%= post.author %></span>
		<span class="date"><%= post.posted_at.strftime("%b %d") %></span>
	</span>
	</h2>
	
	<p class="meta">
		<%= render :partial => "meta", :locals => { :post => post } %>	
	</p>
		
	<div class="entry">
		<%= post.content.html_safe %>
	</div>
</div>
<% end %>

<% end %>

<% content_for :sidebar do %> 
<%= render :partial => "layouts/sidebar" %>
<% end %>

app/views/posts/new.html.erb
<% content_for :title do %> 
Create Post
<% end %>

<% content_for :robots do %> 
<meta name="robots" content="noarchive"/>
<meta name="robots" content="noindex, nofollow"/>
<% end %>

<% content_for :modstyles do %> 
<%= stylesheet_link_tag "modstyles" %>
<% end %>

<% content_for :modjs do %>
<%= javascript_include_tag "showdown" %>
<%= javascript_include_tag "wmd" %>
<%= javascript_include_tag "textarearesizer" %>
<%= javascript_include_tag "elastic" %>
<% end %>

<div class="post">
	<h2><a href="#" class="article">Title me wisely brave citizen</a> 
	<span class="nobreak">
		<span class="author"><%= current_user.name %></span>
		<span class="date"><%= Time.now.strftime("%b %d") %></span>
	</span>
	</h2>
	
	<p class="meta"><a href="#">Laisser un commentaire</a></p>
		
	<div id="wmd-preview" class="entry"></div>
</div><!--post-->

<% content_for :sidebar do %> 
<div class="sidebar">
	<%= form_for(@post) do |f| %>
	<div id="title-container">
		<%= f.text_field :title %> 
		<p>/titre-de-votre-article</p>
	</div>
	
	<div id="wmd-container">
	<div id="wmd-button-bar"></div>

	<%= f.text_area :markdown, :id => "wmd-input", :cols => "92", :rows => "15" %>
	
	</div><!--wmd-container-->
	
	<ul class="options form-submit">
		<li><%= f.submit "Publier l'article", :name => "save_post", :confirm => "Publier l'article ?" %></li>
		<li class="right"><%= f.submit "Enregistrer le brouillon", :id => "draft_submit", :name => "save_draft" %></li>
	</ul>
	<% end %> 
</div><!--sidebar-->
<% end %>

app/views/posts/show.html.erb
<% content_for :title do %><%= @post.title %><% end %>

<% content_for :description do %><%= description(@post.content) %><% end %>

<% if current_user %>
<% content_for :robots do %> 
<meta name="robots" content="noarchive"/>
<meta name="robots" content="noindex, nofollow"/>
<% end %>
<% end %>

<% content_for :adminbar_left do %> 

<li><%= link_to "Modifier l'article", edit_post_path(@post) %></li>

<% if @post.commentable %>

<li>
<%= form_for(@post) do |f| %>
<div><%= f.hidden_field :commentable, :value => "false" %></div>
<div><%= image_submit_tag "lightbulb-on.png", :class => "comments-toggle", :title => "Commentaires autorisés", :alt => "Commentaires autorisés" %></div>
<% end %>
</li>

<% else %>

<li>
<%= form_for(@post) do |f| %>
<div><%= f.hidden_field :commentable, :value => "true" %></div>
<div><%= image_submit_tag "lightbulb-off.png", :class => "comments-toggle", :title => "Commentaires fermés", :alt => "Commentaires fermés" %></div>
<% end %>
</li>

<% end %>

<% end %>

<% content_for :adminbar_right do %> 
<li class="right"><%= link_to "Supprimer l'article", post_path(@post), :confirm => "Are you sure you want to delete this post?", :method => :delete, :class => "delete" %></li>
<% end %>

<div class="post">
	<h2><%= link_to @post.title, @post, :class => "article" %>
	<span class="nobreak">
		<span class="author"><%= @post.author %></span>
		<span class="date"><%= @post.posted_at.strftime("%b %d") %></span>
	</span>
	</h2>
	
	<p class="meta">
		<%= render :partial => "meta", :locals => { :post => @post } %>
	</p>
		
	<div class="entry">
		<%= @post.content.html_safe %>
	</div><!--entry-->
	
  <ul class="social">    
		<li>
		<script type="text/javascript">
		//<![CDATA[
		(function() {
		document.write('<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="yourtwitteraccount">Tweet</a>');
		var s = document.createElement('SCRIPT'), s1 = document.getElementsByTagName('SCRIPT')[0];
		s.type = 'text/javascript';
		s.async = true;
		s.src = 'http://platform.twitter.com/widgets.js';
		s1.parentNode.insertBefore(s, s1);
		})();
		//]]>
		</script>
		</li>
		
		<li>
		<script type="text/javascript">
		//<![CDATA[
		(function() {
		document.write('<fb:like></fb:like>');
		var s = document.createElement('SCRIPT'), s1 = document.getElementsByTagName('SCRIPT')[0];
		s.type = 'text/javascript';
		s.async = true;
		s.src = 'http://connect.facebook.net/en_US/all.js#xfbml=1';
		s1.parentNode.insertBefore(s, s1);
		})();
		//]]>
		</script>
		</li>
	</ul><!--social-->
	
	<div class="comments_canvas">
		<% if @post.comments.count > 0 %>
    <h2 class="comment_count"><%= pluralize(@post.comments.count, "commentaire") %></h2>
		
		<div id="comments" class="comments">
			<% for comment in @post.comments.all %> 
			<%= render :partial => comment, :locals => { :post => @post } %> 
			<% end %>
		</div><!--comments-->
		<% else %>
		
		<h2 class="comment_count plain"></h2>
		<div id="comments" class="comments"></div><!--comments-->
		<% end %>
		
		<div id="post_a_comment">
		<% if !@post.commentable %>
		<h2 id="comments_closed">Désolé, les commentaires ne sont pas autorisés pour cet article.</h2>
		<% end %>

		<% if @post.commentable %>
		<h2>Laisser un commentaire</h2>
		<%= form_for([@post, @comment], :remote => true) do |f| %>
		<div id="new_comment_canvas">
			<fieldset>
				<div class="form-field">
				<% if current_user %>
					<%= f.text_field :name, :value => current_user.initials, :size => "40" %> 
				<% else %>
					<%= f.text_field :name, :value => "Votre nom", :size => "40" %> 
				<% end %>
				</div>
				
				<div class="form-field">
					<%= f.text_field :email, :value => "Votre adresse Email", :size => "40" %> 
				</div>

				<div class="form-field">
					<%= f.text_field :website, :value => "Votre site web", :size => "40" %> 
				</div>	
			</fieldset>
			
			<fieldset>
				<div class="form-field">
					<%= f.text_area :content, :cols => "55", :rows => "6", :value => "Exprimer-vous." %>
				</div>
			</fieldset>
			
			<fieldset>
				<div class="form-submit">
					<%= f.submit "Laisser mon commentaire", :disable_with => "Post comment" %> <span>ou </span> <%= link_to "voir l'apperçu", preview_post_comments_path(@post), :id => "preview_comment_link", :rel => "nofollow" %>
				</div>
			</fieldset>
		</div><!-- new_comment_canvas -->
		
		<div id="comment_preview_canvas">
			<div id="comment_preview"></div>
			
			<div class="form-submit">
				<%= f.submit "Poster le commentaire", :disable_with => "Poster le commentaire", :id => "comment_submit_preview" %> <span>ou </span> <a id="edit_comment_link" href="#">Modifier</a>
			</div>
		</div><!--comment_preview_canvas-->
		<% end %> 
		<% end %>
		</div><!--post_a_comment-->
		
	</div><!--comments_canvas-->
</div><!--post-->

<% content_for :sidebar do %> 
<%= render :partial => "layouts/sidebar" %>
<% end %>