config/routes.rb
Blogcast::Application.routes.draw do
  root :to => "posts#index"

  resources :posts do
    resources :comments do
      collection do
        post :preview
      end
      member do
        delete :mark_as_spam
      end
    end
    
    resources :spams do
      collection do
        delete :incinerate
      end
      member do
        delete :mark_as_ham
      end
    end
  end
  
  resources :drafts
  
  match 'archives', :to => 'archives#index', :as => :archives, :via => [:get]
  
  match 'admin', :to => 'user_sessions#new', :as => :admin, :via => [:get]
  match 'logout', :to => 'user_sessions#destroy', :as => :logout, :via => [:delete]
  resource :user_sessions
  
  resources :users
  
  match 'sitemap', :to => 'sitemap#index', :via => [:get]
  
  match '*a', :to => 'errors#routing', :via => [:get]
end

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
	<div class="block-content" id="intro">
		<h2><%= link_to "Bloggez autrement.", posts_path %></h2>
		<p>Un moteur de blogging simple et intuitif.</p>
	</div><!--block-content-->
	
	<div class="block-content"  id="search">
		<%= link_to "Blogcast Archive", archives_path %>
		
		<form method="get" action="/search">
			<fieldset>
				<input name="requete" type="text"/>
				<input name="sitesearch" value="http://domain.com/blog" type="hidden"/>
			</fieldset>
		</form>
	</div><!--block-content-->
	
	<p class="subscribe"><a href="#">souscrire à ce blog</a></p>
</div><!--sidebar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="author" content="Blogcast"/>
    <meta name="description" content="<%= yield :description %>"/>
    <title> <%= yield :title %> </title>
    <%= csrf_meta_tag %>
    <%= yield :robots %>
    <%= stylesheet_link_tag "blog" %> <%= yield :modstyles %>
    <!--<link href="images/favicon.ico" rel="Shortcut Icon" type="image/x-icon"/>-->
    <%= auto_discovery_link_tag(:rss, "#") %>
    <% if Rails.env.production? %>
      <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" %>
      <% else %>
        <%= javascript_include_tag "jquery" %>
    <% end %>
    <%= javascript_include_tag "rails" %>
    <script type="text/javascript">jQuery.noConflict();</script> <%= yield :modjs %>
      <%= javascript_include_tag "highlight" %>
      <%= javascript_include_tag "blog" %>
  </head>
  
  <body>
    <% if current_user %>
      <div class="adminbar">
        <ul>
        	<li><%= link_to image_tag("stock_spam.png"), post_spams_path(@current_action == "show" && @current_controller =="posts" ? @post : "0-spam-barbecue"), :class => "spam" %></li>
          <li><%= link_to "Retour au blog","/"%></li>
        	<li><%= link_to "Mes articles", posts_path %></li>
        	<li><%= link_to "Nouvel article", new_post_path %></li>
        	<li><%= link_to "Brouillons", drafts_path %></li>
        	<%= yield :adminbar_left %>
        	<li class="right"><%= link_to "Déconnexion", logout_path, :method => :delete, :class => "delete" %></li>
        	<li class="right"><%= link_to "Uitilisateurs", users_path %></li>
        	<%= yield :adminbar_right %>
        	<li class="right"><em>Bienvenue, <%= current_user.name %></em></li>
        </ul>
      </div><!--adminbar-->
    <% end %>

    <div class="header">
      <% if !current_user %>
        <h1>BlogCast</h1>
      <% end %>
    </div><!-- header -->
    <div class="wrapper">
      <div class="content">
        <%= yield %>
      </div><!--content-->
      <%= yield :sidebar %>
      <br style="clear: both; " /><br /><br />
    </div><!--wrapper-->

    <div class="footer">
    	<p>
		    Copyright © 2011
	  	<span>Version 1.0.0</span>
    	</p>
    </div><!-- footer -->
    <% if Rails.env.production? && !current_user %>
    
      <script type="text/javascript">
  
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'Your Google Analytics Account']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
      </script>
    <% end %>
  </body>
</html>